import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.css'
import { LandingBanner } from '@components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Quintas Dos Church</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <LandingBanner />
      </main>
    </>
  )
}
